### ISSUE TITLE
Cluster deployment fails due to hardcoded unavailable version (1.16)

### ISSUE THREAD

**Issue by n0531m** [GoogleCloudPlatform/datashare-toolkit#512] opened 2021-06-09 06:47 UTC
**Describe the bug**

Deployment fromo marketplace will fail with the following error.

{"ResourceType":"container.v1.cluster","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"No valid versions with the prefix \"1.16\" found.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1/projects/XXXXXX/zones/us-central1-a/clusters","httpMethod":"POST"}}

According to GKE release notes, version 1.16 hard coded into the config is no longer available since May 04. Default is now 1.18
https://cloud.google.com/kubernetes-engine/docs/release-notes#May_04_2021

value 1.16 can be seen hard coded in cluster.py line 26

**Comment by mservidio** [comment] 2021-06-09 18:47
Duplicate of https://github.com/GoogleCloudPlatform/datashare-toolkit/issues/506

**Comment by swilliams11** [comment] 2021-06-09 20:03
Hi @n0531m  It will take a few days before version 0.7.0 is available on the Marketplace, but this issue has already been resolved.

**Closed by swilliams11** 2021-06-09 20:03 UTC
Labels: duplicate

**Comment by swilliams11** [comment] 2021-06-09 20:20
Also, if you need to deploy now you can use the following documentation.
https://github.com/GoogleCloudPlatform/datashare-toolkit/tree/master/marketplace#deploy-datashare-from-command-line

Just make sure to use version 0.7.0 when you execute those commands.

**Comment by n0531m** [comment] 2021-06-10 02:39
thanks for the followup. 

If I clone the repo and follow the instructions above, the deployment will fail due to missing files. (deploy_ui_cloud_run.*, deploy_ds_api.*)   Is this intended?

**Comment by n0531m** [comment] 2021-06-10 15:17
Current Marketplace offering is listed as follows with mixed expression of 0.7.0 and 0.6.8. 
It still is hardcoded with GKE 1.16 so assuming the code is at 0.6.8 level

----

Additional details
Runs on: Google Compute Engine
Type: Virtual machines, Single VM
Last updated: 6/10/21
Category: Big data, Financial services
Version: 0.6.8
Operating System: Debian v20200714 LTS
Package contents: Datashare 0.7.0 , Cloud Run on GKE 1.16
Add to Private Catalog: Deployment .zip file

**Comment by swilliams11** [comment] 2021-06-10 15:43
Hi @n0531m Yes, that is an error in the docs. I'll update it.  only get that error if you run the command from the `datashare-toolkit/marketplace/releases` directory. 

Make sure to unzip the 0.7.0 file and then cd into the `vm-solution` directory (the unzipped directory).  That directory has all the necessary files. Also, be sure to update all the properties in the `vm-solution/test_config.yaml` file. 

Yes, the current Marketplace solution will continue to display the old solution (0.6.8) until 0.7.0 is published. It typically takes a several days before it is updated, but you can still deploy using that link above.  

Just a clarification:
There are two version numbers listed because there are effectively 2 code bases. 
1. Marketplace release is at 0.6.8 (code responsible for deploying the Datashare solution into GCP)
2. The Datashare solution has its own release version (0.7.0) 
These code bases evolve independently and so they will be different or they may match as some point in the future, but the version numbers will typically be different.
